### ISSUE TITLE
Missing documenttion abotu different tags

### ISSUE THREAD

**Issue by jalberto** [bitnami/bitnami-docker-ruby#83]
I cannot find in any link or doc the difference between the `prod` tag and the others

**Comment by carrodher** [comment]
Hi, thanks for letting us know. You can find some documentation about production ruby container in the example folder: https://github.com/bitnami/bitnami-docker-ruby/tree/master/example

In the same way, I just created an internal task in order to add more information regarding `prod` images into our README

**Comment by jalberto** [comment]
Thanks!
By peeking the Dockerfiles, I can see the main difference is the lack of compilers in the prod image

**Comment by carrodher** [comment]
Sorry for the delay, it was done some time ago, now a new section about prod tags appears in the README: https://github.com/bitnami/bitnami-docker-ruby#what-are-prod-tagged-containers-for
